/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_Hesco;

import java.awt.Color;
import javax.swing.JFrame;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author 0Rank
 */
public class viewHesco extends javax.swing.JFrame {

    /**
     * Creates new form View4health
     */
    public viewHesco() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        lbljudul = new javax.swing.JLabel();
        btnDataSiswa = new javax.swing.JButton();
        btnDataObat = new javax.swing.JButton();
        lblicon = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelDataSiswa = new javax.swing.JPanel();
        lblNmPetugas = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        tbnEdit = new javax.swing.JButton();
        btnTambahData = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtfieldcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataSiswa = new javax.swing.JTable();
        lblDataSiswa = new javax.swing.JLabel();
        exitmenu = new javax.swing.JButton();
        panelDataObat = new javax.swing.JPanel();
        lblNmPetugas1 = new javax.swing.JLabel();
        btnRefresh1 = new javax.swing.JButton();
        tbnEdit1 = new javax.swing.JButton();
        btnTambahObat = new javax.swing.JButton();
        btnCari1 = new javax.swing.JButton();
        txtfieldcari1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataSiswa1 = new javax.swing.JTable();
        lblDataObat = new javax.swing.JLabel();
        exitmenu2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4Health");
        setUndecorated(true);

        bodyPanel.setBackground(new java.awt.Color(51, 86, 160));
        bodyPanel.setPreferredSize(new java.awt.Dimension(950, 550));

        menuPanel.setBackground(new java.awt.Color(51, 86, 160));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        lbljudul.setBackground(new java.awt.Color(51, 255, 153));
        lbljudul.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        lbljudul.setForeground(new java.awt.Color(255, 255, 255));
        lbljudul.setText("SMKN 4 BANDUNG");

        btnDataSiswa.setBackground(new java.awt.Color(0, 153, 204));
        btnDataSiswa.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        btnDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnDataSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/datasiswa.png"))); // NOI18N
        btnDataSiswa.setText("Data Siswa");
        btnDataSiswa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDataSiswa.setContentAreaFilled(false);
        btnDataSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDataSiswa.setIconTextGap(20);
        btnDataSiswa.setMaximumSize(new java.awt.Dimension(289, 209));
        btnDataSiswa.setPreferredSize(null);
        btnDataSiswa.setSelected(true);
        btnDataSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataSiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataSiswaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDataSiswaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDataSiswaMouseReleased(evt);
            }
        });
        btnDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSiswaActionPerformed(evt);
            }
        });

        btnDataObat.setBackground(new java.awt.Color(0, 153, 204));
        btnDataObat.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        btnDataObat.setForeground(new java.awt.Color(255, 255, 255));
        btnDataObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/dataobat.png"))); // NOI18N
        btnDataObat.setText("Data Obat");
        btnDataObat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDataObat.setContentAreaFilled(false);
        btnDataObat.setIconTextGap(20);
        btnDataObat.setSelected(true);
        btnDataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataObatActionPerformed(evt);
            }
        });

        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo hesco.png"))); // NOI18N

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbljudul)
                .addGap(79, 79, 79))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDataObat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblicon))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblicon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbljudul, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnDataObat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(51, 255, 153));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setLayout(new java.awt.CardLayout());

        panelDataSiswa.setPreferredSize(new java.awt.Dimension(615, 518));

        lblNmPetugas.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        lblNmPetugas.setText("Hallo Petugas ..");

        btnRefresh.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 11)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setBorderPainted(false);
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.setPreferredSize(new java.awt.Dimension(107, 50));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tbnEdit.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 11)); // NOI18N
        tbnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/edit.png"))); // NOI18N
        tbnEdit.setText("Edit");
        tbnEdit.setBorderPainted(false);
        tbnEdit.setContentAreaFilled(false);
        tbnEdit.setPreferredSize(new java.awt.Dimension(80, 50));

        btnTambahData.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 11)); // NOI18N
        btnTambahData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/tambah data.png"))); // NOI18N
        btnTambahData.setText("Tambah Data");
        btnTambahData.setBorderPainted(false);
        btnTambahData.setContentAreaFilled(false);
        btnTambahData.setPreferredSize(new java.awt.Dimension(135, 50));
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        btnCari.setText("Cari");

        txtfieldcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldcariActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        tblDataSiswa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblDataSiswa.setFont(new java.awt.Font("Humnst777 BT", 0, 11)); // NOI18N
        tblDataSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "NIS", "Nama", "Jenis Kelamin", "Ket. Sakit", "Tanggal", "Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDataSiswa.setSelectionBackground(new java.awt.Color(204, 255, 102));
        tblDataSiswa.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblDataSiswa);
        if (tblDataSiswa.getColumnModel().getColumnCount() > 0) {
            tblDataSiswa.getColumnModel().getColumn(6).setResizable(false);
        }

        lblDataSiswa.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblDataSiswa.setForeground(new java.awt.Color(51, 86, 160));
        lblDataSiswa.setText("Data Siswa");

        exitmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/exit.png"))); // NOI18N
        exitmenu.setContentAreaFilled(false);
        exitmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataSiswaLayout = new javax.swing.GroupLayout(panelDataSiswa);
        panelDataSiswa.setLayout(panelDataSiswaLayout);
        panelDataSiswaLayout.setHorizontalGroup(
            panelDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataSiswaLayout.createSequentialGroup()
                        .addGroup(panelDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDataSiswaLayout.createSequentialGroup()
                                .addComponent(lblNmPetugas)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelDataSiswaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtfieldcari, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDataSiswaLayout.createSequentialGroup()
                        .addGroup(panelDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDataSiswaLayout.createSequentialGroup()
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDataSiswaLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(lblDataSiswa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelDataSiswaLayout.setVerticalGroup(
            panelDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataSiswaLayout.createSequentialGroup()
                .addGroup(panelDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataSiswaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(exitmenu))
                    .addGroup(panelDataSiswaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDataSiswa)))
                .addGap(22, 22, 22)
                .addComponent(lblNmPetugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(txtfieldcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(panelDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );

        mainPanel.add(panelDataSiswa, "card2");

        panelDataObat.setPreferredSize(new java.awt.Dimension(615, 518));

        lblNmPetugas1.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        lblNmPetugas1.setText("Hallo Petugas ..");

        btnRefresh1.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 11)); // NOI18N
        btnRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/refresh.png"))); // NOI18N
        btnRefresh1.setText("Refresh");
        btnRefresh1.setBorder(null);
        btnRefresh1.setContentAreaFilled(false);
        btnRefresh1.setPreferredSize(new java.awt.Dimension(105, 50));
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        tbnEdit1.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 11)); // NOI18N
        tbnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/edit.png"))); // NOI18N
        tbnEdit1.setText("Edit");
        tbnEdit1.setBorder(null);
        tbnEdit1.setContentAreaFilled(false);
        tbnEdit1.setPreferredSize(new java.awt.Dimension(80, 50));

        btnTambahObat.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 11)); // NOI18N
        btnTambahObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/tambahobat.png"))); // NOI18N
        btnTambahObat.setText("Tambah Obat");
        btnTambahObat.setBorder(null);
        btnTambahObat.setContentAreaFilled(false);
        btnTambahObat.setPreferredSize(new java.awt.Dimension(135, 50));
        btnTambahObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahObatActionPerformed(evt);
            }
        });

        btnCari1.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 11)); // NOI18N
        btnCari1.setText("Cari");

        txtfieldcari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldcari1ActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);
        jScrollPane2.setToolTipText("");

        tblDataSiswa1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblDataSiswa1.setFont(new java.awt.Font("Humnst777 BT", 0, 11)); // NOI18N
        tblDataSiswa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "Kode Obat", "Nama Obat", "Manfaat", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDataSiswa1.setSelectionBackground(new java.awt.Color(204, 255, 102));
        tblDataSiswa1.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblDataSiswa1);

        lblDataObat.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblDataObat.setForeground(new java.awt.Color(51, 86, 160));
        lblDataObat.setText("Data Obat");

        exitmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/exit.png"))); // NOI18N
        exitmenu2.setContentAreaFilled(false);
        exitmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataObatLayout = new javax.swing.GroupLayout(panelDataObat);
        panelDataObat.setLayout(panelDataObatLayout);
        panelDataObatLayout.setHorizontalGroup(
            panelDataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataObatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataObatLayout.createSequentialGroup()
                        .addGroup(panelDataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataObatLayout.createSequentialGroup()
                                .addComponent(lblNmPetugas1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfieldcari1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(panelDataObatLayout.createSequentialGroup()
                        .addGroup(panelDataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDataObatLayout.createSequentialGroup()
                                .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDataObatLayout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(lblDataObat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelDataObatLayout.setVerticalGroup(
            panelDataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataObatLayout.createSequentialGroup()
                .addGroup(panelDataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataObatLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(exitmenu2)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataObatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDataObat)
                        .addGap(18, 18, 18)))
                .addComponent(lblNmPetugas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari1)
                    .addComponent(txtfieldcari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(panelDataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(panelDataObat, "card3");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldcari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldcari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldcari1ActionPerformed

    private void btnDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSiswaActionPerformed
        // TODO add your handling code here:
//        btnDataSiswa.setBorder(null);
//        btnDataSiswa.setVisible(true);
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(panelDataSiswa);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnDataSiswaActionPerformed

    private void btnDataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataObatActionPerformed
        // TODO add your handling code here:
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(panelDataObat);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnDataObatActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void btnDataSiswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataSiswaMousePressed
        // TODO add your handling code here:
        btnDataSiswa.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnDataSiswaMousePressed

    private void btnDataSiswaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataSiswaMouseReleased
        // TODO add your handling code here:
        btnDataSiswa.setBackground(new Color(51,86,160));
    }//GEN-LAST:event_btnDataSiswaMouseReleased

    private void btnDataSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataSiswaMouseEntered
        // TODO add your handling code here:
        btnDataSiswa.setBackground(new Color(51,86,160));
    }//GEN-LAST:event_btnDataSiswaMouseEntered

    private void btnDataSiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataSiswaMouseExited
        // TODO add your handling code here:
         btnDataSiswa.setBackground(new Color(51,86,160));
    }//GEN-LAST:event_btnDataSiswaMouseExited

    private void exitmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitmenuActionPerformed

    private void txtfieldcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldcariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTambahObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahObatActionPerformed
        // TODO add your handling code here: btn tambah data obat
        TambahObat tb =  new TambahObat();
        tb.setVisible(true);
    }//GEN-LAST:event_btnTambahObatActionPerformed

    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
        // TODO add your handling code here: button tambah data siswa
        TambahDataSiswa ds = new TambahDataSiswa();
        ds.setVisible(true);
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void exitmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenu2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitmenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewHesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewHesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewHesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewHesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewHesco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCari1;
    private javax.swing.JButton btnDataObat;
    private javax.swing.JButton btnDataSiswa;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JButton btnTambahObat;
    private javax.swing.JButton exitmenu;
    private javax.swing.JButton exitmenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDataObat;
    private javax.swing.JLabel lblDataSiswa;
    private javax.swing.JLabel lblNmPetugas;
    private javax.swing.JLabel lblNmPetugas1;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lbljudul;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel panelDataObat;
    private javax.swing.JPanel panelDataSiswa;
    private javax.swing.JTable tblDataSiswa;
    private javax.swing.JTable tblDataSiswa1;
    private javax.swing.JButton tbnEdit;
    private javax.swing.JButton tbnEdit1;
    private javax.swing.JTextField txtfieldcari;
    private javax.swing.JTextField txtfieldcari1;
    // End of variables declaration//GEN-END:variables

    private Color RGBColor(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
